<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">

<head>
	<title><?= $this->title; ?> | Chris Kankiewicz - Web Design, Graphic Design, Code</title>
	<link rel="shortcut icon" href="/images/icons/favicon.png" />

	<link rel="stylesheet" type="text/css" href="/css/rebase.css" />
	<link rel="stylesheet" type="text/css" href="/css/structure.css" />
	<link rel="stylesheet" type="text/css" href="/css/colorbox.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />
	<? if($this->css): ?>
		<link rel="stylesheet" type="text/css" href="<?= $this->css; ?>" />
	<? endif; ?>
	<!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="/css/ie8.css" /><![endif]-->
	<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/css/ie7.css" /><![endif]-->
	<!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" /><![endif]-->

	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/jquery.colorbox.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
		$("a[rel='colorbox']").colorbox({maxWidth: "90%", maxHeight: "90%", opacity: ".5"});
	});
	</script>

	<meta name="keywords" content="Chris Kankiewicz, web design, graphics design, code, digital photography" />
</head>

<body>

<div id="wrap">
	<div id="main" class="clearfix">

		<div id="header" class="clearfix">
			<div class="width-constraint">
				<div id="site-title" class="left"><a href="/">Chris <span class="green">Kankiewicz</span></a></div>
				<div id="site-tag" class="right">Web Design, Graphic Design, Code</div>
			</div>
		</div>

		<div id="wrapper" class="clearfix">
			<div id="content-wrapper">
				<div id="content-top"></div>
				<div id="content-main">
					<ul id="site-navigation" class="clearfix">
						<li <? if(strtolower($this->title) == 'home'): ?> class="active" <? endif; ?>><a href="/" id="home" class="first">Chris</a></li>
						<li <? if(strtolower($this->title) == 'blog'): ?> class="active" <? endif; ?>><a href="/blog" id="blog">Blog</a></li>
						<li <? if(strtolower($this->title) == 'portfolio'): ?> class="active" <? endif; ?>><a href="/portfolio" id="portfolio">Portfolio</a></li>
						<li <? if(strtolower($this->title) == 'resume'): ?> class="active" <? endif; ?>><a href="/resume" id="resume">Resume</a></li>
						<li <? if(strtolower($this->title) == 'photography'): ?> class="active" <? endif; ?>><a href="/photography" id="photography">Photography</a></li>
						<li <? if(strtolower($this->title) == 'contact'): ?> class="active" <? endif; ?>><a href="/contact" id="contact" class="last">Contact</a></li>
					</ul>
					<h2 id="page-title"><?= $this->title; ?></h2>
					<?= $this->layout()->content; ?>
				</div>
				<div id="content-bottom"></div>
			</div>
		</div>

	</div>
</div>

<div id="footer">

	<div id="footer-top" class="clearfix">
		<div class="width-constraint">
			<ul id="social-icons" class="clearfix">
				<li>
					<a href="http://github.com/PHLAK">
						<img src="images/social_icons/github.png" alt="GitHub"/>
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">GitHub</span>
								<span class="popup-text">http://github.com/PHLAK</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://stackoverflow.com/users/27025">
						<img src="images/social_icons/stack_overflow.png" alt="Stack Overflow"/>
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Stack Overflow</span>
								<span class="popup-text">http://stackoverflow.com/users/27025</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://twitter.com/PHLAK">
						<img src="images/social_icons/twitter.png" alt="Twitter" />
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Twitter</span>
								<span class="popup-text">http://twitter.com/PHLAK</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://digg.com/users/PHLAK">
						<img src="images/social_icons/digg.png" alt="Digg" />
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Digg</span>
								<span class="popup-text">http://digg.com/users/PHLAK</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://flickr.com/photos/kankie">
						<img src="images/social_icons/flickr.png" alt="Flickr" />
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Flickr</span>
								<span class="popup-text">http://flickr.com/photos/kankie</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://www.hulu.com/profiles/phlak">
						<img src="images/social_icons/hulu.png" alt="Hulu" />
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Hulu</span>
								<span class="popup-text">http://www.hulu.com/profiles/phlak</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://steamcommunity.com/id/PHLAK">
						<img src="images/social_icons/steam.png" alt="Steam Community"/>
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Steam Community</span>
								<span class="popup-text">http://steamcommunity.com/id/PHLAK</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
				<li>
					<a href="http://www.facebook.com/ckankiewicz" title="Facebook">
						<img src="images/social_icons/facebook.png" alt="Facebook" />
						<span class="social-icon-popup">
							<span class="popup-top">
								<span class="popup-title">Facebook</span>
								<span class="popup-text">http://www.facebook.com/ckankiewicz</span>
							</span>
							<span class="popup-bottom"></span>
						</span>
					</a>
				</li>
			</ul>
		</div>
	</div>

	<div id="footer-bottom" class="clearfix">
		<div class="width-constraint">
			<div class="left">
				Copyright &copy; <?= date('Y'); ?> <b>&middot;</b>
				Chris Kankiewicz <b>&middot;</b>
				Some Rights Reserved
			</div>
			<div class="right text-right">
				Valid <a href="http://validator.w3.org/check?uri=http://www.directorylister.com">XHTML</a>
				and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> <b>&middot;</b>
				Web design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a>
			</div>
		</div>
	</div>

</div>

</body>
</html>
