<div id="home-content" class="clearfix">
	<div class="left">
		<p><strong>Welcome to ChrisKankiewicz.com!</strong> My name is Chris Kankiewicz and I am a web geek. I'm a self taught web developer / designer proficient with (X)HTML, CSS, PHP and JavaScript. I am the sole maintainer of this site and work on it in my spare time for fun.</p>

		<div class="hr"><hr/></div>
		<h3>About Me</h3>
		<p>Born beautiful Phoenix, Arizona, I attended a local elementary school and middle school, and graduated from Shadow Mountain High School, class of 2005.</p>
		<p>Originally, I wasn't particularly interested in computers, just computer games, until early on in high school when my friend Charles Bock introduced me to the concept of upgrading your computers internal components to make them run better/faster/stronger.  He was also the one to introduce me to HTML and basic web design principles.  Throughout high school I further researched and learned about computers and their internal workings, both hardware and software.  After graduating high school I had a much more advanced knowledge of computers and the web then most of the other students at my school.</p>
		<p>During the summer between my Sophomore and Senior years, I started taking classes at DeVry University.  After graduating from high school I started attending DeVry full time.  During my time in college I worked mostly for Jannenga Enterprises doing front end web and graphic design.  It was there that my web development skills grew the most.  I graduated from DeVry in February of 2008 with a Bachelors of Science degree in Network and Communication Management.  Soon after graduating I got a job working with PetSmart providing internal technical support.</p>
		<p>On August 2nd, 2008 I married Sarah Elizabeth Abbott and moved into her place where I currently reside.  Sarah and I own two cats, Mimsy and Quincy, and two dogs, Jade and Tyke.  I'm still working for PetSmart, and enjoy designing websites on the side.  My other interests include PC gaming, lock picking, miscellaneous hacking, and going to the movies.</p>
	</div>

	<div class="right">
		<a href="/images/chris-kankiewicz.jpg" title="Chris Kankiewicz" id="chris-kankiewicz" rel="colorbox">
			<img src="/images/chris-kankiewicz_thumb.jpg" alt="Chris Kankiewicz" />
		</a>

		<div id="twitter-wrapper">
			<h3>Chris's Tweets</h3>
			<div id="tweets">
				<ul id="twitter_update_list"><li><!-- BLANK --></li></ul>
			</div>
		</div>
	</div>
</div>

<!-- TWITTER -->
<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/PHLAK.json?callback=twitterCallback2&amp;count=5"></script>
<!-- /TWITTER -->