<? echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">


<head>
	<title><?= $this->title; ?> | Chris Kankiewicz - Web Design, Graphic Design, Code</title>
	<link rel="shortcut icon" href="/images/icons/favicon.png" />

	<link rel="stylesheet" type="text/css" href="/css/rebase.css" />
	<link rel="stylesheet" type="text/css" href="/css/structure.css" />
	<link rel="stylesheet" type="text/css" href="/css/thickbox.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />
	<!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="/css/ie8.css" /><![endif]-->
	<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/css/ie7.css" /><![endif]-->
	<!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" /><![endif]-->

    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery.thickbox.js"></script>

	<meta name="keywords" content="Chris Kankiewicz, web design, code, digital photography" />
</head>

<body>

<div id="wrap">
	<div id="main" class="clearfix">

		<div id="header" class="clearfix">
			<div class="width-constraint">
				<div id="site-title"><a href="/"><img src="images/chris-kankiewicz-logo-small.png" alt="Chris Kankiewicz"/></a></div>
				<ul id="site-navigation">
					<li class="active"><a href="/" id="home" class="tab">Chris</a></li>
					<li><a href="/portfolio" id="portfolio" class="tab">Portfolio</a></li>
					<li><a href="/resume" id="resume" class="tab">Resume</a></li>
					<li><a href="/photography" id="photography" class="tab">Photography</a></li>
					<li><a href="/contact" id="contact" class="tab">Contact</a></li>
				</ul>
			</div>
		</div>

		<div id="content-wrapper" class="clearfix">
			<div class="width-constraint">
				<div id="content">
					<h2 id="page-title"><?= $this->title; ?></h2>
					<?= $this->layout()->content; ?>
				</div>
				<div id="right-bar">
					<div id="stack-overflow-wrapper">
						<script src="http://stackoverflow.com/users/flair/27025.js?theme=default" type="text/javascript"></script>
					</div>
					<div id="twitter-wrapper">
						<h3>Chris's Tweets</h3>
						<div id="tweets">
							<ul id="twitter_update_list"><li><!-- BLANK --></li></ul>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

<div id="footer">

	<div id="footer-top" class="clearfix">
		<div class="width-constraint">
			<ul id="social-icons" class="clearfix">
				<li>
					<a href="http://github.com/PHLAK">
						<img src="images/social_icons/github.png" alt="GitHub"/>
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>GitHub</h5>
								<p>http://github.com/PHLAK</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://stackoverflow.com/users/27025">
						<img src="images/social_icons/stack_overflow.png" alt="Stack Overflow"/>
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Stack Overflow</h5>
								<p>http://stackoverflow.com/users/27025</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://twitter.com/PHLAK">
						<img src="images/social_icons/twitter.png" alt="Twitter" />
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Twitter</h5>
								<p>http://twitter.com/PHLAK</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://digg.com/users/PHLAK">
						<img src="images/social_icons/digg.png" alt="Digg" />
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Digg</h5>
								<p>http://digg.com/users/PHLAK</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://flickr.com/photos/kankie">
						<img src="images/social_icons/flickr.png" alt="Flickr" />
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Flickr</h5>
								<p>http://flickr.com/photos/kankie</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://www.hulu.com/profiles/phlak">
						<img src="images/social_icons/hulu.png" alt="Hulu" />
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Hulu</h5>
								<p>http://www.hulu.com/profiles/phlak</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://steamcommunity.com/id/PHLAK">
						<img src="images/social_icons/steam.png" alt="Steam Community"/>
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Steam Community</h5>
								<p>http://steamcommunity.com/id/PHLAK</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
				<li>
					<a href="http://www.facebook.com/ckankiewicz" title="Facebook">
						<img src="images/social_icons/facebook.png" alt="Facebook" />
						<div class="social-icon-popup">
							<div class="popup-top">
								<h5>Facebook</h5>
								<p>http://www.facebook.com/ckankiewicz</p>
							</div>
							<div class="popup-bottom"></div>
						</div>
					</a>
				</li>
			</ul>
		</div>
	</div>

	<div id="footer-bottom" class="clearfix">
		<div class="width-constraint">
			<div class="left">
				Copyright &copy; 2008 - <?= date('Y'); ?> <b>&middot;</b>
				<a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a> <b>&middot;</b>
				Some Rights Reserved
			</div>
			<div class="right text-right">
				Valid <a href="http://validator.w3.org/check?uri=http://www.directorylister.com">XHTML</a>
				and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> <b>&middot;</b>
				Web design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a>
			</div>
		</div>
	</div>

</div>

<!-- TWITTER -->
<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/PHLAK.json?callback=twitterCallback2&amp;count=5"></script>
<!-- /TWITTER -->

</body>
</html>
